### ISSUE TITLE
Error on from_pretrained

### ISSUE THREAD

**Issue by pilot7747** [Fraser-Greenlee/transformer-vae#3]
Hello!

I can't load the pretrained model due to the following error.
`model = T5_VAE_Model.from_pretrained('t5-vae-poet')`

```
OSError: Can't load config for 't5-vae-poet'. Make sure that:

- 't5-vae-poet' is a correct model identifier listed on 'https://huggingface.co/models'

- or 't5-vae-poet' is the correct path to a directory containing a config.json file
```

As I understand you don't provide the pre-trained model. Am I right?

**Comment by Fraser-Greenlee** [comment]
Hey sorry for the late reply on this.

Yeah I don't have one ready yet but I will be training one soon!
